#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"


# kamui

### 1. handle ssh keys

[ ! -d ~/.ssh ] && mkdir ~/.ssh
if [ $(ls ~/.ssh | wc -l) -eq 0 ]
then
    cp /mnt/e/FSs/LL5_2022-02-22_00-07-40/home/kamui/.ssh/* ~/.ssh
    chmod 0600 ~/.ssh/*
else
    echo "SSH keys weren't copied because ~/.ssh is not empty, you should add them manually"
fi

